package darkhax.moreswordsmod;

import java.util.Arrays;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;

import darkhax.moreswordsmod.core.proxy.CommonProxy;
import darkhax.moreswordsmod.core.util.Config;
import darkhax.moreswordsmod.core.util.Language;
import darkhax.moreswordsmod.core.util.Reference;
import darkhax.moreswordsmod.items.ItemRegistry;

@Mod(modid = Reference.id, name = Reference.name, version = Reference.version)
@NetworkMod(clientSideRequired = true, serverSideRequired = false)

public class MoreSwords{
	
	@SidedProxy(serverSide=Reference.common, clientSide=Reference.client)
	public static CommonProxy proxy;
	
	@Mod.Instance(Reference.id)
    public static MoreSwords instance;
	
	public static Language lang = Language.getInstance();
	
	@Mod.PreInit
	public void PreInit(FMLPreInitializationEvent event){	
		
		getModMeta(event.getModMetadata());
		Config.createConfig(event);
		ItemRegistry.load();
	}
	
	@Mod.Init
	public void Init(FMLInitializationEvent event){
		
		ItemRegistry.load();
	}
	
	@Mod.PostInit
	public void PostInit(FMLPostInitializationEvent event){
	}
	
	private void getModMeta(ModMetadata meta){
		
		meta.authorList = Arrays.asList(new String[] { "Darkhax" });
	    meta.autogenerated = false;
	    meta.credits = "Maintained by Darkhax";
	    meta.description = "This mod adds various swords into minecraft.";
	    meta.url = "http://www.minecraftforum.net/topic/1138477-147-sspsmp-more-swords-mod-99-000-download-now-with-pedestals/";
	}
}
